version: '2'

services:
    web:
        restart: always
        build: ./web
        expose:
            - '8000'
        links:
            - postgres:postgres
        volumes:
            - /usr/src/app
            - /usr/src/app/static
        command: /usr/local/bin/gunicorn wui.wsgi:application -w 2 -b :8000

    nginx:
        restart: always
        build: ./nginx
        ports:
            - '80:80'
        volumes:
            - /www/static
        volumes_from:
            - web
        links:
            - web:web

    postgres:
        restart: always
        image: postgres:9.5
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
