version: '2'

services:
    web:
        restart: always
        image: dockerparkour_web:latest
        build: ./web
        expose:
            - '8000'
        links:
            - postgres:postgres
        volumes:
            - usr_src_app_media:/usr/src/app/media
            - usr_src_app_staticfiles:/usr/src/app/staticfiles
        command: /usr/local/bin/gunicorn wui.wsgi:application -w 2 -b :8000

    nginx:
        restart: always
        image: dockerparkour_nginx:latest
        build: ./nginx
        ports:
            - '80:80'
        volumes_from:
            - web
        links:
            - web:web

    postgres:
        restart: always
        image: postgres:9.5
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
    usr_src_app_media:
    usr_src_app_staticfiles:
